### ISSUE TITLE
Use timelines

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#14]
Event timelines should be shown on tags and authors.  Can probably remove the scoped timeline page once these are in place.

**Comment by bmaland** [comment]
Keeping the scoped timeline url, since it can be used for e.g. feeds: /tags/graphics/timeline.atom

**Comment by hadley** [comment]
Why wouldn't we use /tags/graphics.atom ?

**Comment by bmaland** [comment]
I guess we could, if they should have the same content. They would probably end up pretty much the same anyway, so you're probably right.
