### ISSUE TITLE
"Imports" packages should be included in uses list (and display Priority tags)

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#16]
E.g. http://crantastic.org/packages/ggplot2  imports reshape (>= 0.8.0), plyr (>= 0.1.8), splines, MASS, RColorBrewer, grid, proto

**Comment by bmaland** [comment]
The cron scripts will from now on also parse the Imports fields, so this can easily be done for upcoming package versions

**Comment by hadley** [comment]
Great.  Are there any other fields from the description file that we're currently not parsing?

**Comment by bmaland** [comment]
We are currently parsing:

```
[:title, :license, :description, :author,
 :maintainer, :date, :url, :depends, :suggests, :imports]
```

Following http://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file, "Enhances" and "Priority" are the main fields we don't parse as of yet, should I add those? There's also some more exotic fields that we don't parse: "Collate", "LazyLoad", "ZipData", "OS_type" and "Type"

**Comment by hadley** [comment]
We should definitely add enhances.  Priority would be nice so we could automatically tag base & recommended packages.

**Comment by bmaland** [comment]
Done. How do you suggest priority should be shown? A regular tag or something different?

**Comment by hadley** [comment]
A regular tag I think - but styled differently like the task views.

**Comment by bmaland** [comment]
Priorities are now added automatically. Look at http://crantastic.org/packages/boot for an example. (I added blue to the color scheme, feel free to change it)

**Comment by hadley** [comment]
Awesome.  I like the blue :)
