### ISSUE TITLE
Package list on homepage doesn't match site colour scheme

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#18]

**Comment by bmaland** [comment]
Maybe something like this? http://crantastic.org/packages

**Comment by hadley** [comment]
Hmm. Could we try the green instead?

**Comment by bmaland** [comment]
Trying the green now: http://crantastic.org/packages

**Comment by hadley** [comment]
Hmmm.  That didn't look right to me either, so I played around myself and made a few tweaks.

**Comment by bmaland** [comment]
Nice, looks much cleaner now
