### ISSUE TITLE
Package navigation on homepage should remember position

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#19]
If you click on a package and then return to the homepage with the backbutton, your position in the list is lost.  It would be nice if you went back to the previous state.  Similarly, it would be nice to be able to bookmark a package search on the front page.

**Comment by bmaland** [comment]
Page number is now remembered: hadley@3783a78d6daa64aed1f9c44e39d5d1ae3e49757b

Will attempt to create a bookmark function as well, but haven't figured out how the UI should be yet.

**Comment by hadley** [comment]
This is along the lines of what I was thinking: http://www.onjava.com/pub/a/onjava/2005/10/26/ajax-handling-bookmarks-and-back-button.html.  But I'm sure there must be a modern jqueryish/railish way of doing this.

**Comment by bmaland** [comment]
Ah, I see. http://www.mikage.to/jquery/jquery_history.html will probably work when browsing back and forth between result pages and packages, which is better than the current session based solution. It will take a little more effort to make it unobtrusive when used together with will_paginate, but I'll give it a shot.

For bookmarking search terms a link/button on the page would be required (afaik). Maybe a small icon placed to the immediate right of the search box could work out.

**Comment by hadley** [comment]
Yeah, something like that was what I was thinking.  If it's a pain don't worry about bookmarking the search - but I thought you could do something with location.href in js - i.e. ?page=3&q=excel

**Comment by bmaland** [comment]
Yes, but then the page would reload. Thats why they use the # sign for URLs in these history plugins, since that prevents the browser from doing a reload. However, the Ajax loading of result pages in the search results isn't really useful, so I've implemented a new solution in hadley@a6725f3151efce49faee95434df25243c55a07f0. Browser history for page number and search term works for both JS and non-JS clients, since it relies on proper URLs instead of the #-based ones.

Give it a try and let me know what you think.

**Comment by hadley** [comment]
It's just about there - it only doesn't work when do you do a single search with no navigation.

**Comment by bmaland** [comment]
Yeah that can't be done automatically, afaik. And if it could, it would create a lot of entries in browser history (one for each character entered into the search field). However it does work if you hit the Enter key when you're happy with your search - you'll get a pretty ugly URL though

**Comment by hadley** [comment]
Oh good point!  One alternative would be to wait a couple of seconds after they had finished typing, or only save when they navigated away from the page, but that's probably a lot of work for little gain.

**Comment by bmaland** [comment]
Agreed, I'll leave this as it is for the time being
