### ISSUE TITLE
Should be able to "un-use" a package

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#33]
i.e. I accidentally voted for the ctv package and now I can't unvote.

**Comment by bmaland** [comment]
Implemented in hadley@1894e91f5a2c16dc10b1114708468fca28920c8a (the underlying code already supported "un-using", it just wasn't visible in the UI)

I'm not 100% sure on the visuals, the space limitations makes it hard. Suggestions?

**Comment by hadley** [comment]
I think that works.  I'll think about about it.
