### ISSUE TITLE
All packages should have link to "R graphical manual"

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#34]
e.g. for HMisc the link is http://bm2.genes.nig.ac.jp/RGM2/package.php?query=Hmisc&scope=name

**Comment by hadley** [comment]
Or rather http://bm2.genes.nig.ac.jp/RGM2/pkg.php?p=Hmisc

**Comment by bmaland** [comment]
Added in hadley@cf9bd01813a6ab54d10a3842b11006b4866a1082

**Comment by hadley** [comment]
Looks good.
