### ISSUE TITLE
Filter timeline events

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#36]
It would be useful to have functionality on top timeline even that combined subsequent events by a given user.  This would make the code in TimelineEventsHelper easier, and would make it easier to collapse other events like:
- multiple votes (will be a particular problem when get R integration going)
- multiple taggings with the same tag

**Comment by bmaland** [comment]
Good idea - the UI could be modelled after GitHub's timeline (using JavaScript to collapse the events client-side)

**Comment by hadley** [comment]
I was thinking it would need to be done client side so it would affect both the html and rss views.

**Comment by bmaland** [comment]
Yep I only meant the contract/expand stuff, e.g. the show/hide links GitHub uses to let users watch the individual commits in the timeline. I'll give it a shot, I'm not 100% sure yet on how the implementation should look

**Comment by bmaland** [comment]
Thinking more closely on this, I'm not sure if I'm 100% following. Could you give an example on how this should look on the site?

**Comment by hadley** [comment]
I'm not sure how it would work from a db perspective but I'm thinking of a sort of state machine which would queue up matching events and then spit out the combined HTML description. For example, it would listening to user events until the user changes and then emit a single event that said eg "Hadley has tagged these
packages and rated this this package and uses these packages".  It would also filter out update events when they follow a new package event. Does that make sense?

**Comment by bmaland** [comment]
The grouping part is done (hadley@77ec9fc31e98a67e68072b23bea248a04e050f20) and seems to work well, I hope to finish up the HTML part soon too. The challenge is to find out how the existing helper code can be shared between the HTML generation for a single regular timeline event, and a grouped/filtered event.

**Comment by bmaland** [comment]
Think I finally got it right (I hope :). Have a look at the main page and suggest further changes if needed.

**Comment by hadley** [comment]
Looks great!
