### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#37]
For people who don't use rss, it should be possible to sign up for notifications via email.  (I think there are some third party sites that do this, so it would probably just be a link to one of these)

**Comment by hadley** [comment]
Along similar lines, maybe it would be useful to have weekly digests that reported on everything that changed in the last week.  This might be something we could send to r-help to both promote new packages and crantastic.

**Comment by bmaland** [comment]
For the email notifications, Feedburner's rss-to-email functionality is probably the way to go. As a bonus we'll also get subscriber stats etc for the feeds. Shall I set up Feedburner  with the cranatic google account, or do you prefer to have it in your account?

(I'll create a separate issue for the weekly digest)

**Comment by hadley** [comment]
Cranatic please

**Comment by bmaland** [comment]
Done in hadley@686033cdc7340c2615c3ac47c9bfd4b617161496

The text/link might need some tweaking, though

**Comment by hadley** [comment]
Looks good.  I'll probably tweak the display a bit when I have a few free minutes.
