### ISSUE TITLE
Sign in page should open as ajax dialog

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#4]
It should be necessary to navigate away from the current page to log in.  Instead an ajax dialog box should pop up.

**Comment by hadley** [comment]
Ideally the login page should be integrated into the sign up and presented in the same way.  See reddit.com for a nice example of how to do this.

**Comment by bmaland** [comment]
First version implemented in hadley@2b1018b250dc57ba5274d3d02036ab111f2d34a6

It does integrate with RPX signup, but this probably should be made more explicit

**Comment by hadley** [comment]
Maybe the button should be log in / sign up?  And you'll be moving the existing login form to that page in due course?

**Comment by bmaland** [comment]
I'll try, its a bit crude to edit the HTML in the RPX widget though. Hopefully it isn't a breach of terms to modify their JS widget (I had to download the code from their server and uploaded a modified version to crantastic). I've sent them an email about this and hopefully they'll respond soon.

**Comment by bmaland** [comment]
Reimplemented in hadley@3cd4a9e1de4d0fc45fb24e2e4ea12ed7fe4d3346

Maybe there should be a small header or text below the regular login form, explaining that it is for existing logins? Feedback welcome

**Comment by hadley** [comment]
I think it looks good.  Maybe display "OR" between the RPX vs. original?
