### ISSUE TITLE
Crantastic should tweet package releases and updates

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#41]

**Comment by bmaland** [comment]
I created a Twitter account a while ago to support Twitter OAuth logins, we could use that account for this as well.

http://twitter.com/cranatic

**Comment by bmaland** [comment]
Implemented in hadley@ad4217e20fd9b05959151ae8099c3014bf06d07c

Note that it is not live on Heroku yet -- I'll let you review the format/wording of the tweets first. :)

**Comment by hadley** [comment]
Great.  Make sure to tag them with #rstats, and definitely we only want package events, not all user events.

**Comment by hadley** [comment]
Sorry - didn't read your message properly.  Just tweaked the output.  Should be good to go now.

**Comment by bmaland** [comment]
Cool - it's now live :)
