### ISSUE TITLE
Weekly digests

### ISSUE THREAD

**Issue by bmaland** [hadley/crantastic#44]
"Along similar lines, maybe it would be useful to have weekly digests that reported on everything that changed in the last week. This might be something we could send to r-help to both promote new packages and crantastic."

Good idea - this can be triggered via the cron task once per week. The digests could be stored in the database so they can be browsed online and provided through a feed, and maybe automatically mailed to r-help (unless that breaches with their usage policies).

**Comment by hadley** [comment]
We might also want daily digests for twitter, we don't want to flood #rstats.  I'll keep thinking about it.

**Comment by bmaland** [comment]
First stab: hadley@17c0d8f787e7159b3e42a49fdce94ace1daed546

The digests will be available from http://crantastic.org/weekly_digest/:year-:week_number (and maybe a separate feed?)

Currently just displaying new packages and new versions, what else should be included? Definitely reviews, anything else?

**Comment by hadley** [comment]
Jus reviews I think. And yes a weekly feed would be a good idea.

**Comment by bmaland** [comment]
Digest for the current week: http://crantastic.org/weekly_digests/2009-32

(The digests are created dynamically, so it will be updated until the week is over)

An index page is coming up (both html and feed)

**Comment by bmaland** [comment]
The index page and the feed is now up, but there isn't a link to /weekly_digests on the main site yet. (btw, if you want to see the feed stats, visit http://feedburner.google.com/ with the cranatic account)

**Comment by hadley** [comment]
Looks good.  One minor suggestion: can you display the dates the week spans rather than the number?  

We'll also need a .txt view suitable for inclusion in an email

**Comment by hadley** [comment]
I've created text view - can you set it up to send to r-help once a week?

**Comment by bmaland** [comment]
Should be finished now, we'll have to see on Sunday if the message actually reaches r-help, though

**Comment by bmaland** [comment]
Now displaying the dates in the html view: http://crantastic.org/weekly_digests/2009-34

Does that look ok? Maybe the dates also should be included in the txt/mail views.

**Comment by hadley** [comment]
Just checked in (bb58ec8d6b1fb2f80ec54aced19a610cd5f28d1b) what I was thinking of

**Comment by bmaland** [comment]
I think this can be closed now
