### ISSUE TITLE
Daily updates for twitter

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#45]
Still not sure about the format.  Maybe two tweets:

New: adsfsda, asdfadsf, eyrteyt, http://crantastic/daily/20080901
Update: asdfadsf, asdfsdf, http://crantastic/daily/20080901

If more than 140 characters, remove the last package and add ...  (repeat if necessary)

**Comment by bmaland** [comment]
```
>> DailyDigest.find_by_param(20090804).tweets
=> { :versions=>"Update: alr3, clustvarsel, dlnm, FrF2, IDPmisc, labeltodendro, quantreg, Rcpp, reporttools, sendplot, ... http://crantastic/daily/20090804",
       :packages=>"New: bclust, interval, Rniftilib, YieldCurve. http://crantastic/daily/20090804"}
```

Like that? Should we use a hashtag? (#rupdates maybe)

**Comment by hadley** [comment]
Yes, that looks good.  And lets try rstats again - I think at most 2 tweets a day should be ok.  We'll see how it goes

**Comment by bmaland** [comment]
Created a cron task that will run 30 minutes before midnight every night -- we'll see how it works out tonight. :)

The rake task got added in hadley@e802e169ad619c38c7aae94b286877e9591018de

**Comment by hadley** [comment]
Looks great.  Thanks!
