### ISSUE TITLE
Display the most popular packages

### ISSUE THREAD

**Issue by bmaland** [hadley/crantastic#49]
I.e. the ones with most registered users, ala http://rubytrends.com/

**Comment by hadley** [comment]
And similarly, the packages with the highest rankings. 

Should have call to action nearby: i.e. "Disagree - vote for your favourite package here"

**Comment by bmaland** [comment]
Now showing the top 5 on the front page, as well as the full list on http://crantastic.org/popcon

**Comment by bmaland** [comment]
This has been implemented
