### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#6]
Should have rss (or atom) feeds for every page that lists multiple packages.  There should be a choice between viewing all updates or seeing just new packages.

**Comment by bmaland** [comment]
It would be nice with a feed for the timelines.

**Comment by bmaland** [comment]
I've added feeds for tags/task views: http://crantastic.org/task_views/Bayesian

If you like that solution I can add timeline feeds to authors/users/the home page as well. Will add a feed for just package releases as well.

**Comment by hadley** [comment]
Awesome!  Yes please for authors/users/home page.  And for individual packages too?  For package related events (e.g. release, upgrade,  tagging(?)) could you please include the package description?  And maybe an RSS icon in the sidebar?

**Comment by bmaland** [comment]
These changes are now pushed to the site. If taggings should include package description, I guess ratings and reviews should do the same

**Comment by hadley** [comment]
Looks great.  Thanks!

**Comment by bmaland** [comment]
I've added two new feeds: one for just new packages, and a more comprehensive one for new version releases. These are available via auto-discovery from all pages. The contents of the version feed could be tweaked, but currently it includes description, readme, changelog, and news.

**Comment by hadley** [comment]
Looks great.  Thanks.
