### ISSUE TITLE
Recent activity

### ISSUE THREAD

**Issue by hadley** [hadley/crantastic#7]
The homepage should display recent activity on the site:
- new reviews/ratings
- recently updated or added packages
- newly tagged packages

...

**Comment by bmaland** [comment]
I'm actually working on this, using the [timeline_fu plugin](http://github.com/giraffesoft/timeline_fu/tree/master), as described in [this blog post](http://giraffesoft.ca/blog/2009/02/26/how-to-use-timelinefu-building-an-activity-feed-for-a-social-application.html)

The current homepage isn't very exiting so it will be a nice addition!

**Comment by bmaland** [comment]
First stab: http://crantastic.org/ . Currently includes reviews, ratings, and taggings. Will add packages as well. A feed should be produced, adding a comment for that in Issue #6.

**Comment by hadley** [comment]
Looks great.  And could a filtered version of that view appear on a users profile page as well?

**Comment by bmaland** [comment]
Yeah, I'm thinking that it also would be cool with a scoped version that could be used from multiple locations. E.g. for user profiles, packages, tags, etc. by just appending "/timeline" to the URL. It could prove to be a general solution for feeds, if the controller generates the feeds automatically along with the timeline.

**Comment by hadley** [comment]
A scoped version would be very nice.

I'm not sure whether it will have enough information to generate good RSS feeds.  It would be fine for informational feeds, but for (e.g.) the new packages feed, you'd want to include more information from the package description.

**Comment by bmaland** [comment]
I've implemented scoped timelines - it's activated for users, packages, tags, and task views. They're currently not explicitly linked from anywhere, though.

**Comment by bmaland** [comment]
Closing this since package releases/upgrades now are included.
